"""Validation script: compare the Python RLDDM port against the original R code.

Prerequisites
-------------
1. Run `Rscript validate_rlddm.R` first to generate the reference CSV files.
2. The R script sources ../Full_R/cognitive_modelling_course_RLDDM_full.r,
   generates a fixed task environment, simulates data, and saves the fit.

This script then reads those reference files, runs the same data through the
Python implementation (`rlddm_run`), and checks that the trial-by-trial values,
drift rates, prediction errors, and log-likelihoods match the R output.

Because the DDM sampler uses different RNG streams in R and Python, we do NOT
compare `rlddm_simulate` outputs directly. Instead we compare `rlddm_run`, which
is deterministic given observed choices/RTs/outcomes and parameters.
"""

import numpy as np
import pandas as pd

from rlddm import rlddm_run, rlddm_log_lik


def main():
    # Load reference data generated by R
    task_env = pd.read_csv("validation_task_environment.csv").to_numpy()
    data = pd.read_csv("validation_simulated_data.csv")
    r_values = pd.read_csv("validation_values.csv").to_numpy()
    r_drifts = pd.read_csv("validation_drifts.csv").to_numpy().ravel()
    r_pred_errors = pd.read_csv("validation_prediction_errors.csv").to_numpy().ravel()
    r_log_lik = pd.read_csv("validation_log_lik.csv").to_numpy().ravel()
    pars_df = pd.read_csv("validation_pars.csv")
    pars = {col: float(pars_df[col].iloc[0]) for col in pars_df.columns}

    print("Reference parameters from R:")
    for k, v in pars.items():
        print(f"  {k} = {v}")

    # Run the deterministic fit in Python
    py_fit = rlddm_run(data, pars, initial_values=(0.0, 0.0))

    # Compare trial-by-trial quantities
    print("\n--- Comparison against R reference ---")
    print(f"Values  : max abs diff = {np.nanmax(np.abs(py_fit['values'] - r_values)):.6e}")
    print(f"Drifts  : max abs diff = {np.max(np.abs(py_fit['drifts'] - r_drifts)):.6e}")
    print(f"PEs     : max abs diff = {np.max(np.abs(py_fit['prediction_errors'] - r_pred_errors)):.6e}")
    print(f"Log-liks: max abs diff = {np.max(np.abs(py_fit['log_lik'] - r_log_lik)):.6e}")
    print(f"Summed log-lik (Python) = {py_fit['summed_log_lik']:.6f}")
    print(f"Summed log-lik (R)      = {np.sum(r_log_lik):.6f}")

    # Also check the convenience wrapper
    ll = rlddm_log_lik(data, pars)
    print(f"\nrlddm_log_lik wrapper   = {ll:.6f}")

    # Sanity thresholds
    tol = 1e-4
    ok = (
        np.nanmax(np.abs(py_fit["values"] - r_values)) < tol
        and np.max(np.abs(py_fit["drifts"] - r_drifts)) < tol
        and np.max(np.abs(py_fit["prediction_errors"] - r_pred_errors)) < tol
        and np.max(np.abs(py_fit["log_lik"] - r_log_lik)) < tol
    )
    print("\nValidation:", "PASS" if ok else "FAIL")


if __name__ == "__main__":
    main()
